development: 
  adapter: postgresql 
  database: blog_development 
  encoding: unicode 
  user: action 
  host: localhost 
  pool: 5 
  timeout: 5000


test:
  adapter: postgresql 
  database: blog_test
  encoding: unicode 
  user: action 
  host: localhost 
  pool: 5 
  timeout: 5000

production:
  adapter: postgresql 
  database: blog_production
  encoding: unicode 
  pool: 5 
  timeout: 5000
